[package]
name = "arca-setup"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "El instalador de Arca"
publish = false

[[bin]]
name = "arca-setup"
path = "src/main.rs"

[dependencies]
arca-core.workspace = true
arca-zip.workspace = true
gpui = { package = "gpui-pre", version = "0.3", default-features = false }
sys-locale = "0.3"

[target."cfg(windows)".dependencies]
winreg = "0.56"
arca-notify = { path = "../arca-notify" }

[target."cfg(windows)".dependencies.gpui_platform]
package = "gpui-pre-platform"
version = "0.3"

[target.'cfg(target_os = "linux")'.dependencies.gpui_platform]
package = "gpui-pre-platform"
version = "0.3"
features = ["wayland", "x11"]

[target.'cfg(target_os = "macos")'.dependencies.gpui_platform]
package = "gpui-pre-platform"
version = "0.3"
features = ["font-kit"]

[target."cfg(windows)".build-dependencies]
winresource = "0.1"
