[package]
name = "arca-iso"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Read-only ISO 9660 reader for Arca"

[dependencies]
arca-core.workspace = true
rayon.workspace = true
tempfile = "3"

[lints.rust]
unsafe_code = "forbid"
