[package]
name = "arca-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Tipos comunes y lectura acotada para Arca"

[dependencies]
crc32fast.workspace = true
cap-std = "4.0.3"
cap-fs-ext = "4.0.3"

[dev-dependencies]
tempfile = "3"

[lints.rust]
unsafe_code = "forbid"
