"""Regenerate or check the published license texts for the RAR adapter branch."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[1]
TARGETS = (
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
)
LEGAL_NAMES = ("LICENSE", "LICENCE", "COPYING", "COPYRIGHT", "NOTICE")


def cargo(*args):
    return subprocess.check_output(["cargo", *args], cwd=ROOT, text=True)


def render():
    metadata = json.loads(cargo("metadata", "--locked", "--format-version", "1"))
    selected = set()
    for target in TARGETS:
        tree = cargo("tree", "--locked", "-p", "arca-rar", "--features", "rar",
                     "--target", target, "-e", "normal,build", "--prefix", "none",
                     "-f", "{p}")
        for line in tree.splitlines():
            match = re.match(r"^(\S+) v(\S+)", line)
            if match:
                selected.add(match.groups())

    packages = sorted(
        (p for p in metadata["packages"]
         if p["source"] and (p["name"], p["version"]) in selected),
        key=lambda p: (p["name"], p["version"]),
    )
    assert any(p["name"] == "rars" for p in packages), "missing RAR backend"
    output = [
        "RAR adapter: third-party license texts and notices",
        "Generated by: python3 packaging/rar-notices.py",
        "",
        "Scope: arca-rar's normal/build dependencies, including arca-core's",
        "shared dependencies, for the five release targets listed below.",
        "This is a conservative union, not a claim that every dependency is",
        "linked into every artifact or an inventory of the whole application.",
        "No RAR/UnRAR reference executable or research tree is bundled.",
        "Upstream license declarations are reproduced, not independently certified.",
        "See docs/plans/rars-0.10.0-distribution.md for the provenance observations.",
        "",
        *TARGETS,
        "",
    ]
    texts = {}
    for package in packages:
        name = f"{package['name']} {package['version']}"
        source = Path(package["manifest_path"]).parent
        files = sorted(p for p in source.rglob("*") if p.is_file()
                       and p.name.upper().startswith(LEGAL_NAMES))
        if package["license_file"]:
            files = sorted(set(files) | {source / package["license_file"]})
        assert files, f"no published license files for {name}"
        output += [name, f"Declared license: {package['license']}",
                   f"Source: {package['source']}"]
        for path in files:
            content = path.read_bytes()
            digest = hashlib.sha256(content).hexdigest()
            texts[digest] = content.decode("utf-8")
            output.append(f"  {path.relative_to(source).as_posix()} -> SHA-256 {digest}")
        output.append("")
    output += ["License texts (identical upstream files share one section)", ""]
    for digest, content in sorted(texts.items()):
        output += [f"===== SHA-256 {digest} =====", content, ""]
    return ("\n".join(output).rstrip("\n") + "\n").encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    destination = ROOT / "RAR-NOTICES.txt"
    if args.check:
        if not destination.exists() or destination.read_bytes() != rendered:
            raise SystemExit("RAR-NOTICES.txt is stale; run python3 packaging/rar-notices.py")
        print("RAR license bundle matches the locked dependency sources")
    else:
        destination.write_bytes(rendered)
        print(f"Wrote {destination.name} ({len(rendered)} bytes)")


if __name__ == "__main__":
    main()
